### ISSUE TITLE
Add jq to Dependencies

### ISSUE THREAD

**Issue by erichlf** [arnaupv/nvim-devcontainer-cli#19]
`jq` is apparently a dependency and wasn't listed in the dependencies, so that should be updated.

**Comment by arnaupv** [comment]
Hi @erichlf thanks for opening the issue. I've just added `jq` as a dependency

**Comment by arnaupv** [comment]
@erichlf  I'm wondering if you are actively using this tool. If that's the case it would be great if you share with me some improvement points. Continue writing issues is the best way, thanks!

**Comment by erichlf** [comment]
I am attempting to use it. At the moment I am having trouble getting it to work correctly. I will put in a few bug reports feature requests etc. I will likely also submit some patches along with those. I would really like to drop VSCode like the bad habit it is.

**Comment by arnaupv** [comment]
Great @erichlf , I've been using it in a daily basis for the last year and it works like a charm! It will be great to make it more robust and make it easier to setup. Happy to help! 🚀
