### ISSUE TITLE
Don't bind-mount unnecessarily

### ISSUE THREAD

**Issue by erichlf** [arnaupv/nvim-devcontainer-cli#25]
It isn't clear to me why you are having the devcontainer bind mount things like the user's .gitconfig and github-copilot. If the user wants these mounted then they should put this in their devcontainer file.

**Comment by arnaupv** [comment]
I'm proposing a PR above. It's true it would be nice to have some general mounts that could be added in the nvim plugin config, so they do not need to be added into all the devcontainer config. What do you think @erichlf ?
